config/routes.rb
Rails.application.routes.draw do
  devise_for :subscribers, controllers: { omniauth_callbacks: 'subscribers/omniauth_callbacks' }
  root to: 'homes#show'
  resource :home, only: :show
  get '/users/auth/spotify/ios_callback' => redirect('/')

  resources :playlists, only: :index do
    resources :playlist_watches, only: :create
  end
  resources :playlist_watches, only: :index do
    resources :playlist_snapshots, only: :create
  end
  resources :artist_appearances, only: :index
  resources :oh_my_rockness_syncs, only: :create
end

app/models/artist_appearance.rb
class ArtistAppearance < ApplicationRecord
  belongs_to :artist_watch
  has_many :song_watches, through: :artist_watch
  belongs_to :show_snapshot_band
  has_one :show_snapshot, through: :show_snapshot_band
  delegate :show, to: :show_snapshot
  delegate :name, to: :show_snapshot_band

  scope :upcoming, -> { where('starting_at > ?', Time.zone.now) }
  scope :by_date, -> { joins(:show_snapshot).merge(ShowSnapshot.by_date) }
end

app/controllers/artist_appearances_controller.rb
class ArtistAppearancesController < ApplicationController
  def index
    @latest_oh_my_rockness_sync = OhMyRocknessSync.latest
    @artist_appearances =
      current_subscriber
      .artist_appearances
      .upcoming
      .by_date
      .includes(
        :show_snapshot_band,
        :show_snapshot
      )
    @song_watches = current_subscriber.song_watches
  end
end

app/views/artist_appearances/index.html.erb
<h1>Artist appearances</h1>
<div>
  <%= link_to 'Sync now', oh_my_rockness_syncs_path, method: :post, class: 'btn btn-secondary btn-sm', role: 'button' %>
  Last synced at <%= @latest_oh_my_rockness_sync&.created_at || 'never' %>
</div>
<br />
<%- @artist_appearances.each do |artist_appearance| %>
  <div class="card card-list-item">
    <div class="card-body">
      <h5 class="card-title">
        <%= link_to artist_appearance.show.summary, artist_appearance.show.url %>
      </h5>
      <%- @song_watches.merge(artist_appearance.song_watches).each do |song_watch| %>
        <div>
          <%= link_to song_watch.name, song_watch.spotify_track_url %>
          by
          <%= link_to artist_appearance.name, song_watch.spotify_artist_url_for_appearance(artist_appearance) %>
          on
          <%= link_to song_watch.playlist_watch.name, song_watch.playlist_watch.spotify_playlist_url %>
        </div>
      <%- end %>
    </div>
  </div>
<%- end %>