config/routes.rb
Rails.application.routes.draw do
  devise_for :subscribers, controllers: { omniauth_callbacks: 'subscribers/omniauth_callbacks' }
  root to: 'homes#show'
  resource :home, only: :show
  get '/users/auth/spotify/ios_callback' => redirect('/')

  resources :playlists, only: :index do
    resources :playlist_watches, only: :create
  end
  resources :playlist_watches, only: :index do
    resources :playlist_snapshots, only: :create
  end
  resources :artist_appearances, only: :index
  resources :oh_my_rockness_syncs, only: :create
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OhMyPlaylists</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <nav class="navbar navbar-light bg-light navbar-expand">
      <%= link_to "OhMyPlaylists", home_path, class: "navbar-brand" %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Artist appearances", artist_appearances_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Playlist watches", playlist_watches_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Playlists", playlists_path, class: "nav-link" %>
        </li>
      </ul>
    </nav>
    <p class="alert alert-primary" role="alert"><%= notice %></p>
    <p class="alert alert-danger" role="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
</html>